sudo: false

language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - pypy

install:
  - pip install -r requirements.txt --upgrade
  - pip install -r requirements.remote.txt --upgrade
  - pip install -r requirements.robotshell.txt --upgrade
  - pip install robotframework-python3
  - pip install zetup[commands] --upgrade
  - pip install pytest --upgrade
  - pip install tox --upgrade
  - zetup install

script:
  - zetup test
  - py.test -vv test
  - zetup tox
